// RelationOS Core – Enhanced Edition 2025
// Auto-generated by RelationOS Bootstrapper

namespace RelationOS.Core;

/// <summary>
/// Represents a relationship in the ontology system.
/// </summary>
public interface IRelation
{
    /// <summary>
    /// Unique identifier for the relation
    /// </summary>
    string Id { get; }
    
    /// <summary>
    /// Human-readable name of the relation
    /// </summary>
    string Name { get; }
    
    /// <summary>
    /// Domain classification of the relation
    /// </summary>
    RelationDomain Domain { get; }
    
    /// <summary>
    /// Confidence score from harvesting (0.0 - 1.0)
    /// </summary>
    double Confidence { get; }
    
    /// <summary>
    /// Source standard or specification
    /// </summary>
    string SourceStandard { get; }
    
    /// <summary>
    /// When this relation was harvested
    /// </summary>
    DateTime HarvestedAt { get; }
}

/// <summary>
/// Domain classification for relations
/// </summary>
public enum RelationDomain
{
    Unspecified = 0,
    Structural,
    Traceability,
    Behavioral,
    Interface,
    Safety,
    Security,
    Temporal,
    Functional,
    NonFunctional,
    Uncategorized
}

/// <summary>
/// Repository for accessing harvested relations
/// </summary>
public interface IRelationRepository
{
    /// <summary>
    /// Get all relations
    /// </summary>
    IEnumerable<IRelation> GetAll();
    
    /// <summary>
    /// Get relations by domain
    /// </summary>
    IEnumerable<IRelation> GetByDomain(RelationDomain domain);
    
    /// <summary>
    /// Search relations by name pattern
    /// </summary>
    IEnumerable<IRelation> SearchByName(string pattern);
    
    /// <summary>
    /// Get relations from specific standard
    /// </summary>
    IEnumerable<IRelation> GetByStandard(string standard);
}
